---
- name: Play to experiment with network modules and devices
  hosts: network
  gather_subset: config
  tasks:
    - name: Print the device config to config that fact gathering is using the correct module
      debug:
        msg: "{{ ansible_facts['net_config'] }}"

    - name: Use the ping module to see that it works with network devices
      ping:
        data: "NotPong"
    
    - name: Ise the vyos_ping module to ping servers from vyos node
      vyos_ping:
        dest: "{{ item }}"
        count: 1
      loop:
        - servera
        - serverb
        - serverc
        - serverd

    - name: backup the configuration
      vyos_config:
        backup: True
        backup_options:
          dir_path: "{{ playbook_dir }}/backup"
          filename: vyos-config-latest

    - name: Run a basic command
      vyos_command:
        commands:
          - show version