---
- name: Unsafe Stings demo
  hosts: localhost
  vars_prompt:
    - name: unsafe_string
      prompt: provide some data
      private: False
      unsafe: True
  tasks:
    - name: Create a file containing the user input
      copy:
        content: "{{ unsafe_string }}"
        dest: /tmp/demofile